eureka:
  client:
    register-with-eureka: true
    initial-instance-info-replication-interval-seconds: 20 # 服务启动之后20s后注册到eureka
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:11001/eureka/,http://127.0.0.1:11002/eureka/
  instance:
    status-page-url-path: ${server.servlet.context-path:}/swagger-ui.html
    home-page-url-path: ${server.servlet.context-path:}
    health-check-url-path: ${server.servlet.context-path:}/actuator/health
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

spring:
  sleuth:
    sampler:
      probability: 1.0
    enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  redis:
    host: 127.0.0.1
    port: 6379


auth.secret.jwt:
  public-key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAluLwxcijEHqhls/uad9RLIHKK1CFU9X0lDud/h912RCQVCHBmEgrjKfHbwa6tDrpiFKk+jZmECaiZspEzAwgRLRaXBCY85z/J7SnTj9R8qr7f3oSyK5+X70XP/R3RD0WPhMPUqtyh80YhNMRJEMBFJkRrKVyf7AJHkUnOcIB509J69lqUIMDiJSJOB/MLrtoqOuDlBQSHRG9I+d5MNwwtfaFszfcvocXR3Y+VKuh1f9QmyxJgyMst4zXsVvdfbkkvo/KCsFTWRIuEt2KDmRh3n19fKPWdMu6wWj6yN8jPiu/xjSFCJnp+SBbR0xDzPpbL8ylBpd28SOjrJNoxAvceQIDAQAB'
  private-key: 'MIIEpQIBAAKCAQEAluLwxcijEHqhls/uad9RLIHKK1CFU9X0lDud/h912RCQVCHBmEgrjKfHbwa6tDrpiFKk+jZmECaiZspEzAwgRLRaXBCY85z/J7SnTj9R8qr7f3oSyK5+X70XP/R3RD0WPhMPUqtyh80YhNMRJEMBFJkRrKVyf7AJHkUnOcIB509J69lqUIMDiJSJOB/MLrtoqOuDlBQSHRG9I+d5MNwwtfaFszfcvocXR3Y+VKuh1f9QmyxJgyMst4zXsVvdfbkkvo/KCsFTWRIuEt2KDmRh3n19fKPWdMu6wWj6yN8jPiu/xjSFCJnp+SBbR0xDzPpbL8ylBpd28SOjrJNoxAvceQIDAQABAoIBAD6ANPIIoRszYPoCmaR7X7mK7b6xdPj8OHqqk1BvobZPeSmQbgvxYTC7Uw43gGElwhS4/yOyIubvyffAM20+XKN4/bEDIwhOcRb2axMrgXt+vfzZCSzdsvVfc2EHl9vJXgxKgt9gq2l7WHu0nnYh1zG8Eiksw1gHCE/kn1H6fiVc/Mqm9UAagXyAQRUCGD/u7PWNJFUcWiFPkW4I6kTudDG0bEzCIF+eG4w9WpO6z6TRHKf5gElwzojQxt0efYBviXLJvV836Yqxm8TK92NELa3H6ybdpEjX+Z9wg72Jd0zDIfPyawOkEKNVmOCqdb6K37/n/IEjlHDTINaBrRLKzv0CgYEAyMBKxL6DXmJtIoh7MIykSL9Pg6HCvqaeDH+vC6B4vXCVAQkTdrCZVziiDQfSvnx47/Ot49wZ+b1QHU4t+8hFApwRf2lglxNqanlbXzwH9ydY9lRneaxU1ySWxlg3g4kIhErFHCjqM3GbS+QLACiueNyr9dey1woksGMvBeiKvZcCgYEAwGl8v9BViefB0taAwIrfJfsmAs+ZUD2jXwlr4qjVgbKYURR9xE+iJbFUePWC0zpJAHJ529Tf/VoSooyLwLt4PvgTJQ+kTf2F1H6ik7OYNFdzDalKCONRqfi+rF9BFQHFtPhL0hg/Y1LP/9qSQX3fSKmka2ODL9vo/aAlApl+mG8CgYEAxr9xhpUi1CfX6k96vtcOsqMM4sIcXsnwQWmL8JPf1ZWHP24v4dr3BR4heYscPtBWnyD+ME+xO8oMbeb/qX1drTa8MAswwIFNYrphFskFDdDbx4xKoXBW0mT8DMQ7ubLKRscLnFR5gZLg7+KGbZLZIPlAGfWBrlnxdtvLKytNaGMCgYEAnhyQ9JZgFCir73Nw7cewQ2ez/o9VbsiX3VrCmskeWavG2qm6B31gwxSLU7J7xNOadZGcbXbqcSh5M7XGiaQD1crJAKVv4N66ALnnIvRr2GccFlfMjK0vyDqthLvpoTeJnYKD26stO5MrdRXJJaQnvXAZul1Vyhgtx2y3vQEhNGUCgYEAkMjm6F3w5NkZ+8nXOmcFYtWNRjErwqiytCeh/yWZyOphUjNdDO1v4Y7oriihZzr+QtVwBlify9v8+TheZgOCNnu45mV4U7hlLgGYfhi2pBdP3NiTCHEAtxgHchWmbSbdWHB002nq8Kh2aOLyYuuh2H1KVIjMYPweCSvPs8GqjwA='